{% set name = "clairvoyance" %}
{% set version = "2023.6.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  script: $PYTHON -m pip install --no-deps --ignore-installed .

source:
  url: https://github.com/jolespin/clairvoyance/archive/refs/tags/v{{version}}.tar.gz

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
  run:
    - python >=3.6
    - numpy >=1.13
    - scipy >=1.0
    - pandas >=1.2.4
    - xarray >=0.10.3
    - scikit-learn >=1.0
    - matplotlib >=2
    - seaborn >=0.10.1
    - tqdm >=4.19
    - soothsayer_utils >=2022.6.24

about:
  home: https://github.com/jolespin/clairvoyance
  license: GNU AFFERO GENERAL PUBLIC LICENSE
  license_family: GPL
  summary: 'Feature selection via recursive feature inclusion'
  description: 'Feature selection via recursive feature inclusion'
